### ISSUE TITLE
It does not install templates during installation.

### ISSUE THREAD

**Issue by aerograf** [XoopsModules25x/contact#7] opened 2017-07-01 10:46 UTC
XOOPS 2.5.9 RC1
PHP7

**Comment by mambax7** [comment] 2017-07-01 11:30
No problems here. 
Give us more details about what is not working. 
Is this a new Contact installation, or an update to an existing Contact module?

**Comment by aerograf** [comment] 2017-07-01 17:15
Hello!
When installing the module for a new installation.
Now I'm transferring to the PHP7 site and now I've encountered a problem. Gives an installation and update error. You can look at xoops.shmel.org there too. On the main site the module works fine.
You should have access.
Another request to see the updated modules: uservisit, instruction and evaluate Printliminator :-)

**Comment by mambax7** [comment] 2017-07-01 17:24
The module's templates are set for Bootstrap, so if you change the theme to xBootstrap, it works fine
![image](https://user-images.githubusercontent.com/613686/27764160-8e34b1de-5e60-11e7-8523-669d00c56447.png)

**Comment by aerograf** [comment] 2017-07-01 17:30
Here's what I mean:
![contact](https://user-images.githubusercontent.com/25700040/27764197-14838df6-5e9c-11e7-8939-0661ad5715cb.png)

**Comment by mambax7** [comment] 2017-07-01 19:02
You've made some changes to the module that cause the problem. 
I have installed this version from here, and it worked without any problems. 
Your module is under /contact0
So compare your changes to the original, and try to find out what is different that is causing the issue...

**Comment by aerograf** [comment] 2017-07-01 19:05
Thank you. I'll check it again. But I made changes to xoops_version.php. And I took it from here. I will sort this out...

**Comment by mambax7** [comment] 2017-07-01 19:14
It looks more like the problem is in your language files...

**Comment by aerograf** [comment] 2017-07-01 19:17
Ok

**Comment by mambax7** [comment] 2017-07-01 19:48
It looks like these two lines in modinfo.php are causing problems. When I replaced them with the English version, the module installed just fine. 
//define('_MI_B_CONTACT_MAP_DESC', 'Показать определенное место в Google Maps в качестве XOOPS блока');
define('_MI_B_CONTACT_MAP_DESC', 'Show defined location in Google Maps as XOOPS block');

//define('_MI_B_CONTACT_FORM_MAP_DESC', 'Показать контактную форму вместе с определенным адресом в Google Maps в качестве блока');
define('_MI_B_CONTACT_FORM_MAP_DESC', 'Show contact form together with defined location in Google Maps as block');

**Comment by aerograf** [comment] 2017-07-01 19:53
Miracles...

**Comment by mambax7** [comment] 2017-07-01 20:33
Once you figure out what is wrong there, please let us know, and close it...

**Comment by aerograf** [comment] 2017-07-02 07:12
The problem is in these lines. It does not matter which editor to edit.
I will look for a regularity.

**Closed** 2017-07-02 07:12 UTC
